# Generated by Django 5.1.7 on 2025-03-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.JSONField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='questions',
        ),
    ]
