# Generated by Django 5.1.7 on 2025-04-01 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0004_question_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonPressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='name',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='score',
        ),
        migrations.AddField(
            model_name='playerscore',
            name='player1name',
            field=models.CharField(default='player1', max_length=50),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='player1score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='player2name',
            field=models.CharField(default='player2', max_length=50),
        ),
        migrations.AddField(
            model_name='playerscore',
            name='player2score',
            field=models.IntegerField(default=0),
        ),
    ]
