# Generated by Django 5.1.7 on 2025-04-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0005_buttonpresslog_remove_playerscore_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(),
        ),
    ]
