# Generated by Django 5.1.7 on 2025-04-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0009_alter_question_correctanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctAnswers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
